# Generated by Django 4.2.4 on 2024-01-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cusratingfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusorders',
            name='user',
            field=models.CharField(default='Cust', max_length=200),
        ),
    ]
