# Generated by Django 4.2.4 on 2024-01-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_cusorders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='Cust', max_length=200),
        ),
    ]
